### PR TITLE
Change namespace

### PR DESCRIPTION
**Pull request by michalsn**
**Description**
Change the namespace and all related info to the codeigniter.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [x] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Review by kenjis — APPROVED** [review]
I have not looked at it in detail, but the tests passed.

**Comment by michalsn** [comment]
Thanks for the review. I guess we will have to wait until some basic permissions for members are set to merge.

**Review by lonnieezell — APPROVED** [review]

**Comment by MGatner** [comment]
I'm late to the game here: are you missing merge permissions on this repo?

**Comment by michalsn** [comment]
No, everything is fine now. Thanks!

**Pull request merged**
