### PR TITLE
docs: fix broken DB list in Requirements

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
- fix markdown for mkdocs. See https://queue.codeigniter.com/#requirements

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [] Unit testing, with >80% coverage
- [x] User guide updated
- [] Conforms to style guide

### CODE REVIEW

**Review by maniaba — APPROVED** [review]

**Review by ddevsr — APPROVED** [review]

**Review by datamweb — APPROVED** [review]

**Comment by kenjis** [comment]
@michalsn Merge, please.

**Review by michalsn — APPROVED** [review]

**Comment by michalsn** [comment]
@kenjis Sorry, I thought you had a merge button.

**Comment by kenjis** [comment]
I cannot merge without approval in this repository.

**Comment by michalsn** [comment]
Ok, thanks! I will pay more attention to the PRs that appear here.

**Pull request merged**
